# Generated by Django 2.1.15 on 2021-06-07 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('guidemeapp', '0003_tourguideprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tourguideprofile',
            name='alamat_email',
        ),
        migrations.RemoveField(
            model_name='tourguideprofile',
            name='jenis_kelamin',
        ),
        migrations.RemoveField(
            model_name='tourguideprofile',
            name='tanggal_lahir',
        ),
    ]
